### ISSUE TITLE
cannot go get beyond v1.1.127-0a57a1c

### ISSUE THREAD

**Issue by Gurpartap** [cameronnewman/go-emailvalidation#38]
https://pkg.go.dev/github.com/cameronnewman/go-emailvalidation?tab=versions

The Go package index is not aware of any releases or gitrefs since v2 was released.

So `go get` is fixated to v1.1.127-0a57a1c. There doesn't seem to be an easy way to get the latest release.

Perhaps you need to indicate v2 release: https://blog.golang.org/v2-go-modules

**Comment by cameronnewman** [comment]
Thanks for flagging this, I will take a look
